[general]
import = [
    "~/.config/alacritty/themes/themes/xterm.toml"
]

[window]
# opacity = 0.95

[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

# normal = { family = "FiraCode Nerd Font", style = "Mono Light" }
# bold = { family = "FiraCode Nerd Font", style = "Mono Bold" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }
# bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
